apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff
        image: DOCKERHUB_USER/bff-service
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bff-service
spec:
  selector:
    app: bff
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
