apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-manager-frontend
  labels:
    app: image-manager-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-manager-frontend
  template:
    metadata:
      labels:
        app: image-manager-frontend
    spec:
      containers:
        - name: frontend
          image: your-docker-username/image-manager-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: image-manager-frontend
spec:
  type: LoadBalancer
  selector:
    app: image-manager-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
