name: Deploy to EKS

on:
  workflow_dispatch:  # Permite la ejecución manual

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set environment variables
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: image-manager-frontend
          TAG: latest
          EKS_CLUSTER_NAME: your-eks-cluster
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DEPLOYMENT_FILE: frontend-deployment.yaml
        run: |
          echo "Variables de entorno configuradas correctamente."

      - name: Deploy application
        run: bash deploy.sh
